FROM node:24-bookworm-slim

WORKDIR /usr/src/app

ENV NODE_ENV=production

COPY ./my-dev-portal-api/package*.json ./
RUN npm ci --omit=dev && npm cache clean --force

COPY --chown=node:node ./my-dev-portal-api ./

USER node

EXPOSE 3030
CMD ["node", "app.js"]
