FROM node:24-bookworm-slim

WORKDIR /workspace/my-dev-portal

COPY ./my-dev-portal/package*.json ./
RUN npm ci \
    && npm cache clean --force \
    && chown -R node:node /workspace/my-dev-portal

COPY --chown=node:node ./my-dev-portal ./

USER node

EXPOSE 4000

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "4000"]
