FROM node:24-bookworm-slim

WORKDIR /workspace/my-dev-portal-api

COPY ./my-dev-portal-api/package*.json ./
RUN npm ci \
    && npm cache clean --force \
    && chown -R node:node /workspace/my-dev-portal-api

COPY --chown=node:node ./my-dev-portal-api ./

USER node

EXPOSE 3030

CMD ["npm", "run", "dev"]
